# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kurt/Alloprojects/fludyn

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kurt/Alloprojects/fludyn

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kurt/Alloprojects/fludyn/CMakeFiles /home/kurt/Alloprojects/fludyn/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kurt/Alloprojects/fludyn/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named src

# Build rule for target.
src: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 src
.PHONY : src

# fast build rule for target.
src/fast:
	$(MAKE) -f AlloSystem/CMakeFiles/src.dir/build.make AlloSystem/CMakeFiles/src.dir/build
.PHONY : src/fast

#=============================================================================
# Target rules for targets named src_run

# Build rule for target.
src_run: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 src_run
.PHONY : src_run

# fast build rule for target.
src_run/fast:
	$(MAKE) -f AlloSystem/CMakeFiles/src_run.dir/build.make AlloSystem/CMakeFiles/src_run.dir/build
.PHONY : src_run/fast

#=============================================================================
# Target rules for targets named Gamma

# Build rule for target.
Gamma: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Gamma
.PHONY : Gamma

# fast build rule for target.
Gamma/fast:
	$(MAKE) -f Gamma/AlloSystem-build/CMakeFiles/Gamma.dir/build.make Gamma/AlloSystem-build/CMakeFiles/Gamma.dir/build
.PHONY : Gamma/fast

#=============================================================================
# Target rules for targets named gammaUnitTests

# Build rule for target.
gammaUnitTests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gammaUnitTests
.PHONY : gammaUnitTests

# fast build rule for target.
gammaUnitTests/fast:
	$(MAKE) -f Gamma/AlloSystem-build/CMakeFiles/gammaUnitTests.dir/build.make Gamma/AlloSystem-build/CMakeFiles/gammaUnitTests.dir/build
.PHONY : gammaUnitTests/fast

#=============================================================================
# Target rules for targets named cuttlebone

# Build rule for target.
cuttlebone: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cuttlebone
.PHONY : cuttlebone

# fast build rule for target.
cuttlebone/fast:
	$(MAKE) -f cuttlebone/AlloSystem-build/CMakeFiles/cuttlebone.dir/build.make cuttlebone/AlloSystem-build/CMakeFiles/cuttlebone.dir/build
.PHONY : cuttlebone/fast

#=============================================================================
# Target rules for targets named scratch_interruption

# Build rule for target.
scratch_interruption: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scratch_interruption
.PHONY : scratch_interruption

# fast build rule for target.
scratch_interruption/fast:
	$(MAKE) -f cuttlebone/AlloSystem-build/CMakeFiles/scratch_interruption.dir/build.make cuttlebone/AlloSystem-build/CMakeFiles/scratch_interruption.dir/build
.PHONY : scratch_interruption/fast

#=============================================================================
# Target rules for targets named scratch_recvmsg

# Build rule for target.
scratch_recvmsg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scratch_recvmsg
.PHONY : scratch_recvmsg

# fast build rule for target.
scratch_recvmsg/fast:
	$(MAKE) -f cuttlebone/AlloSystem-build/CMakeFiles/scratch_recvmsg.dir/build.make cuttlebone/AlloSystem-build/CMakeFiles/scratch_recvmsg.dir/build
.PHONY : scratch_recvmsg/fast

#=============================================================================
# Target rules for targets named scratch_sendto

# Build rule for target.
scratch_sendto: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scratch_sendto
.PHONY : scratch_sendto

# fast build rule for target.
scratch_sendto/fast:
	$(MAKE) -f cuttlebone/AlloSystem-build/CMakeFiles/scratch_sendto.dir/build.make cuttlebone/AlloSystem-build/CMakeFiles/scratch_sendto.dir/build
.PHONY : scratch_sendto/fast

#=============================================================================
# Target rules for targets named test_apploop

# Build rule for target.
test_apploop: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_apploop
.PHONY : test_apploop

# fast build rule for target.
test_apploop/fast:
	$(MAKE) -f cuttlebone/AlloSystem-build/CMakeFiles/test_apploop.dir/build.make cuttlebone/AlloSystem-build/CMakeFiles/test_apploop.dir/build
.PHONY : test_apploop/fast

#=============================================================================
# Target rules for targets named test_broadcaster

# Build rule for target.
test_broadcaster: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_broadcaster
.PHONY : test_broadcaster

# fast build rule for target.
test_broadcaster/fast:
	$(MAKE) -f cuttlebone/AlloSystem-build/CMakeFiles/test_broadcaster.dir/build.make cuttlebone/AlloSystem-build/CMakeFiles/test_broadcaster.dir/build
.PHONY : test_broadcaster/fast

#=============================================================================
# Target rules for targets named test_file_watcher

# Build rule for target.
test_file_watcher: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_file_watcher
.PHONY : test_file_watcher

# fast build rule for target.
test_file_watcher/fast:
	$(MAKE) -f cuttlebone/AlloSystem-build/CMakeFiles/test_file_watcher.dir/build.make cuttlebone/AlloSystem-build/CMakeFiles/test_file_watcher.dir/build
.PHONY : test_file_watcher/fast

#=============================================================================
# Target rules for targets named test_log

# Build rule for target.
test_log: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_log
.PHONY : test_log

# fast build rule for target.
test_log/fast:
	$(MAKE) -f cuttlebone/AlloSystem-build/CMakeFiles/test_log.dir/build.make cuttlebone/AlloSystem-build/CMakeFiles/test_log.dir/build
.PHONY : test_log/fast

#=============================================================================
# Target rules for targets named test_maker

# Build rule for target.
test_maker: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_maker
.PHONY : test_maker

# fast build rule for target.
test_maker/fast:
	$(MAKE) -f cuttlebone/AlloSystem-build/CMakeFiles/test_maker.dir/build.make cuttlebone/AlloSystem-build/CMakeFiles/test_maker.dir/build
.PHONY : test_maker/fast

#=============================================================================
# Target rules for targets named test_maker_app

# Build rule for target.
test_maker_app: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_maker_app
.PHONY : test_maker_app

# fast build rule for target.
test_maker_app/fast:
	$(MAKE) -f cuttlebone/AlloSystem-build/CMakeFiles/test_maker_app.dir/build.make cuttlebone/AlloSystem-build/CMakeFiles/test_maker_app.dir/build
.PHONY : test_maker_app/fast

#=============================================================================
# Target rules for targets named test_packet

# Build rule for target.
test_packet: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_packet
.PHONY : test_packet

# fast build rule for target.
test_packet/fast:
	$(MAKE) -f cuttlebone/AlloSystem-build/CMakeFiles/test_packet.dir/build.make cuttlebone/AlloSystem-build/CMakeFiles/test_packet.dir/build
.PHONY : test_packet/fast

#=============================================================================
# Target rules for targets named test_queue

# Build rule for target.
test_queue: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_queue
.PHONY : test_queue

# fast build rule for target.
test_queue/fast:
	$(MAKE) -f cuttlebone/AlloSystem-build/CMakeFiles/test_queue.dir/build.make cuttlebone/AlloSystem-build/CMakeFiles/test_queue.dir/build
.PHONY : test_queue/fast

#=============================================================================
# Target rules for targets named test_receiver

# Build rule for target.
test_receiver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_receiver
.PHONY : test_receiver

# fast build rule for target.
test_receiver/fast:
	$(MAKE) -f cuttlebone/AlloSystem-build/CMakeFiles/test_receiver.dir/build.make cuttlebone/AlloSystem-build/CMakeFiles/test_receiver.dir/build
.PHONY : test_receiver/fast

#=============================================================================
# Target rules for targets named test_selector

# Build rule for target.
test_selector: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_selector
.PHONY : test_selector

# fast build rule for target.
test_selector/fast:
	$(MAKE) -f cuttlebone/AlloSystem-build/CMakeFiles/test_selector.dir/build.make cuttlebone/AlloSystem-build/CMakeFiles/test_selector.dir/build
.PHONY : test_selector/fast

#=============================================================================
# Target rules for targets named test_taker

# Build rule for target.
test_taker: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_taker
.PHONY : test_taker

# fast build rule for target.
test_taker/fast:
	$(MAKE) -f cuttlebone/AlloSystem-build/CMakeFiles/test_taker.dir/build.make cuttlebone/AlloSystem-build/CMakeFiles/test_taker.dir/build
.PHONY : test_taker/fast

#=============================================================================
# Target rules for targets named test_taker_app

# Build rule for target.
test_taker_app: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_taker_app
.PHONY : test_taker_app

# fast build rule for target.
test_taker_app/fast:
	$(MAKE) -f cuttlebone/AlloSystem-build/CMakeFiles/test_taker_app.dir/build.make cuttlebone/AlloSystem-build/CMakeFiles/test_taker_app.dir/build
.PHONY : test_taker_app/fast

#=============================================================================
# Target rules for targets named test_time

# Build rule for target.
test_time: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_time
.PHONY : test_time

# fast build rule for target.
test_time/fast:
	$(MAKE) -f cuttlebone/AlloSystem-build/CMakeFiles/test_time.dir/build.make cuttlebone/AlloSystem-build/CMakeFiles/test_time.dir/build
.PHONY : test_time/fast

#=============================================================================
# Target rules for targets named test_timer

# Build rule for target.
test_timer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_timer
.PHONY : test_timer

# fast build rule for target.
test_timer/fast:
	$(MAKE) -f cuttlebone/AlloSystem-build/CMakeFiles/test_timer.dir/build.make cuttlebone/AlloSystem-build/CMakeFiles/test_timer.dir/build
.PHONY : test_timer/fast

#=============================================================================
# Target rules for targets named allocore

# Build rule for target.
allocore: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 allocore
.PHONY : allocore

# fast build rule for target.
allocore/fast:
	$(MAKE) -f AlloSystem/allocore/CMakeFiles/allocore.dir/build.make AlloSystem/allocore/CMakeFiles/allocore.dir/build
.PHONY : allocore/fast

#=============================================================================
# Target rules for targets named doc

# Build rule for target.
doc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doc
.PHONY : doc

# fast build rule for target.
doc/fast:
	$(MAKE) -f AlloSystem/allocore/CMakeFiles/doc.dir/build.make AlloSystem/allocore/CMakeFiles/doc.dir/build
.PHONY : doc/fast

#=============================================================================
# Target rules for targets named allocoreTests

# Build rule for target.
allocoreTests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 allocoreTests
.PHONY : allocoreTests

# fast build rule for target.
allocoreTests/fast:
	$(MAKE) -f AlloSystem/allocore/unitTests/CMakeFiles/allocoreTests.dir/build.make AlloSystem/allocore/unitTests/CMakeFiles/allocoreTests.dir/build
.PHONY : allocoreTests/fast

#=============================================================================
# Target rules for targets named alloGLV

# Build rule for target.
alloGLV: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 alloGLV
.PHONY : alloGLV

# fast build rule for target.
alloGLV/fast:
	$(MAKE) -f AlloSystem/alloGLV/CMakeFiles/alloGLV.dir/build.make AlloSystem/alloGLV/CMakeFiles/alloGLV.dir/build
.PHONY : alloGLV/fast

#=============================================================================
# Target rules for targets named alloaudio

# Build rule for target.
alloaudio: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 alloaudio
.PHONY : alloaudio

# fast build rule for target.
alloaudio/fast:
	$(MAKE) -f AlloSystem/alloaudio/CMakeFiles/alloaudio.dir/build.make AlloSystem/alloaudio/CMakeFiles/alloaudio.dir/build
.PHONY : alloaudio/fast

#=============================================================================
# Target rules for targets named alloaudioTests

# Build rule for target.
alloaudioTests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 alloaudioTests
.PHONY : alloaudioTests

# fast build rule for target.
alloaudioTests/fast:
	$(MAKE) -f AlloSystem/alloaudio/CMakeFiles/alloaudioTests.dir/build.make AlloSystem/alloaudio/CMakeFiles/alloaudioTests.dir/build
.PHONY : alloaudioTests/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... src"
	@echo "... src_run"
	@echo "... Gamma"
	@echo "... gammaUnitTests"
	@echo "... cuttlebone"
	@echo "... scratch_interruption"
	@echo "... scratch_recvmsg"
	@echo "... scratch_sendto"
	@echo "... test_apploop"
	@echo "... test_broadcaster"
	@echo "... test_file_watcher"
	@echo "... test_log"
	@echo "... test_maker"
	@echo "... test_maker_app"
	@echo "... test_packet"
	@echo "... test_queue"
	@echo "... test_receiver"
	@echo "... test_selector"
	@echo "... test_taker"
	@echo "... test_taker_app"
	@echo "... test_time"
	@echo "... test_timer"
	@echo "... allocore"
	@echo "... doc"
	@echo "... allocoreTests"
	@echo "... alloGLV"
	@echo "... alloaudio"
	@echo "... alloaudioTests"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

